# Generated by Django 6.0.3 on 2026-05-18 00:44

import converter.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=5, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(editable=False, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(editable=False, upload_to=converter.models.user_directory_path)),
                ('size_bytes', models.BigIntegerField(editable=False)),
                ('mime_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.user')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConvertFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('original_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_conversions', to='converter.format')),
                ('output_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_conversions', to='converter.format')),
            ],
            options={
                'verbose_name': 'Convert Format',
                'verbose_name_plural': 'Convert Formats',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('error_message', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='converter.convertformat')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='converter.file')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_file_per_user'),
        ),
        migrations.AddConstraint(
            model_name='convertformat',
            constraint=models.UniqueConstraint(fields=('original_extension', 'output_extension'), name='unique_convert_format'),
        ),
    ]
