services:
  db:
    image: postgres:18.2
    container_name: flask_db_postgres
    restart: "no" 
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"