# Generated by Django 6.0.3 on 2026-03-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.publisher'),
            preserve_default=False,
        ),
    ]
