# Generated by Django 6.0.3 on 2026-03-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('biography', models.TextField(max_length=500)),
                ('auto_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.author')),
            ],
        ),
    ]
