# Generated by Django 6.0.3 on 2026-03-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auto_field',
            new_name='author',
        ),
    ]
